services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 500ms
      retries: 3
      start_period: 500ms
      start_interval: 500ms
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file: ".env"

  backend:
    build:
      context: ../../../backend/Api
      dockerfile: api.Dockerfile.local
    ports:
      - '5100:5100'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../../../backend/Api:/App
    env_file: ".env"

  migrate:
    build:
      context: ../../../backend/Api
      dockerfile: migrations.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ".env"

  frontend:
    build:
      context: ../../../frontend
      dockerfile: Dockerfile.local
    ports:
      - '5273:5273'
    volumes:
      - ../../../frontend:/app
      - /app/node_modules
    env_file: ".env"

volumes:
  postgres_data:
